# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_dto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# import coordinate_pb2 as coordinate__pb2
import src.common.proto_compiled.coordinate_pb2 as coordinate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10player_dto.proto\x12\ttron_game\x1a\x10\x63oordinate.proto\"b\n\tPlayerDTO\x12\x10\n\x08is_alive\x18\x01 \x01(\x08\x12\x19\n\x11\x64isplay_character\x18\x02 \x01(\t\x12(\n\tpositions\x18\x03 \x03(\x0b\x32\x15.tron_game.Coordinateb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'player_dto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYERDTO._serialized_start=49
  _PLAYERDTO._serialized_end=147
# @@protoc_insertion_point(module_scope)
