# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: coordinate.proto, player_dto.proto, game_state.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class Coordinate(betterproto.Message):
    x: int = betterproto.int32_field(1)
    y: int = betterproto.int32_field(2)


@dataclass
class PlayerDTO(betterproto.Message):
    is_alive: bool = betterproto.bool_field(1)
    display_character: str = betterproto.string_field(2)
    positions: List["Coordinate"] = betterproto.message_field(3)


@dataclass
class GameState(betterproto.Message):
    players: List["PlayerDTO"] = betterproto.message_field(1)
